export { default as HomePage } from './home'
export { default as AboutPage } from './about'
export { default as ContactPage } from './contact'
export { default as Booknow } from './booknow'
export { default as PropertiesPage } from './properties'
export { default as MainDashboard } from './admin/dashboard'
export { default as PropertiesDetailsPage } from './properties/PropertiesDetailsPage'
